input_size = 512
model = dict(
    detector=dict(
        type='SingleStageDetector',
        pretrained='open-mmlab://vgg16_caffe',
        neck=None,
        backbone=dict(
            type='SSDVGG',
            input_size=input_size,
            depth=16,
            with_last_pool=False,
            ceil_mode=True,
            out_indices=(3, 4),
            out_feature_indices=(22, 34),
            l2_norm_scale=20),
        bbox_head=dict(
            type='SSDHead',
            in_channels=(512, 1024, 512, 256, 256, 256, 256),
            anchor_generator=dict(
                type='SSDAnchorGenerator',
                scale_major=False,
                input_size=input_size,
                basesize_ratio_range=(0.1, 0.9),
                strides=[8, 16, 32, 64, 128, 256, 512],
                ratios=[[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]))))